### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by AndreSait** [Basharath/FormEasy#4] opened 2023-05-06 16:51 UTC
I've followed every step, and made sure that who can access it is set to "anyone", but I still get blocked by CORS. Any ideas?

`blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Basharath** [comment] 2023-05-06 16:58
Hi, so you have the URL something like this `https://script.google.com/macros/s/<Deployment ID>/exec` ?

Can you share it here? So I can check what's the problem is

**Comment by AndreSait** [comment] 2023-05-07 13:06
I changed to a different email form solution, but here's the URL anyway: "https://script.google.com/macros/s/AKfycbzf7f2idRAk5LmuBv6gOID4wrtm4IWGzzaagEJOpL8olX5vdjpZNEZi9h4-IkhrQY1_/exec"

I noticed now that the emails did come through, and was sent to both the email and the sheets list, but the fetch from the web site still gave the CORS error.

**Comment by Basharath** [comment] 2023-05-07 13:38
I have a couple of projects that are in production using similar link without the cors error. Even I checked now they work fine. 

I'll check how to fix this. For now one can put this fetch POST action in the server or through using serverless functions or in NextJS Api routes.

**Comment by RS156** [comment] 2023-07-30 07:10
Hey, I was also facing the CORS issue using the script. After some searching I found an article which helped me get rid of CORS issue.
https://github.com/tanaikech/taking-advantage-of-Web-Apps-with-google-apps-script#corsinwebapps

Apparently my header was  'Content-Type': 'application/json'. On changing it to  'Content-Type': 'text/plain', it worked without any issues.

**Comment by Basharath** [comment] 2023-07-30 08:11
Request headers were already mentioned in the [example code. ](https://github.com/Basharath/FormEasy#form-submission-using-fetch:~:text=headers%3A%20%7B%0A%20%20%20%20%27Content%2DType%27%3A%20%27text/plain%3Bcharset%3Dutf%2D8%27%2C%0A%20%20%7D%2C)

Try to follow the [usage](https://github.com/Basharath/FormEasy#usage) instructions mentioned in the README to solve this issue. 

Try this out once and if you confirm that it's working fine then we can close this issue @AndreSait

**Comment by aykarageorge** [comment] 2023-08-05 13:59
@Basharath Even I'm facing the issue of CORS:
`Access to fetch at 'https://script.google.com/macros/s/<deployment_id>/exec' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Mine is a static website.

**Comment by Basharath** [comment] 2023-08-05 15:52
Hi @aykarageorge, I created a demo here which you can try out, it works as expected: [FormEasy demo](https://stackblitz.com/edit/js-55dzc8?file=index.html,index.js). Also watch out the [demo tutorial](https://www.youtube.com/watch?v=0u75mtnhifM&ab_channel=DevApt) once.

While deploying the Script, did you deploy it as a WebApp or not please confirm once.

**Comment by aykarageorge** [comment] 2023-08-05 16:39
Hi @Basharath. I redeployed the script. Seems working as no error now. But I do not get data in the sheet, neither email is being sent. Any suggestions?

**Comment by Basharath** [comment] 2023-08-05 17:06
@aykarageorge Just cross check if the request body has the data or not. Also check your form submission.

Here is the [demo Google sheet ](https://docs.google.com/spreadsheets/d/13sGrLUk0ScU1qfRyOZzFG5pnksh7IAiTJw1Eio1jfaE/edit#gid=0)as well along with  [code demo](https://stackblitz.com/edit/js-55dzc8?file=index.html,index.js) for you to confirm the working of this library.

**Comment by aykarageorge** [comment] 2023-08-05 17:15
Thank you @Basharath for the quick response. It definitely works and in no way doubting the work you did here.
I was having issues with the Google reCAPTCHA V3 and the integration.
It is working for me now.

**Comment by Basharath** [comment] 2023-08-05 17:22
Awesome. Thanks for confirming @aykarageorge. 

I hope this issue can be closed now as we have enough details in this for people to check if they face this issue.

**Closed as completed by Basharath** 2023-08-05 17:22 UTC

**Comment by aykarageorge** [comment] 2023-08-06 03:53
One other thing I noticed is, it takes some time (maybe a few hours) after deployment for this issue to get fixed. I created a new APp Script project and tried again. It gave me a CORS error. But after some hours, retrying the same API with no change worked.

**Comment by Basharath** [comment] 2023-08-06 04:30
But the demo Google sheet I created yesterday started accepting the forms without issues instantly. 

In fact all of the forms I created till now for my sites worked without such delay in time. So none of these I could see on my end. 

Also what we are creating is a `WebApp` from Google Sheets which means it can be accessed anywhere, isn't it?

**Comment by aykarageorge** [comment] 2023-08-06 05:28
Yes, right.  It seems like a delay from the App Script end. I tried two times, and both times it took some time to enable CORS. Might be a region-based config thing.
